### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ns-rlewkowicz** [k8snetworkplumbingwg/sriov-network-operator#508]
This all worked great on minikube. Moving to a more productionalized cluster it's all falling apart and very difficult to work with. 

DiscoverSriovDevices() spits out 2 lines (should be more) then spews this 

```
E0919 13:55:29.535370 1515138 writer.go:78] RunOnce(): first writing to node status failed: unable to update node <nil>: Timed out trying to fetch node knode01.foo.bar.baz.com: sriovnetworknodestates.sriovnetwork.openshift.io "knode01.foo.bar.baz.com" not found
```

Finally crashing:

```
I0919 13:55:29.535422 1515138 writer.go:208] writeCheckpointFile(): try to decode the checkpoint file
I0919 13:55:29.535442 1515138 writer.go:211] writeCheckpointFile(): write checkpoint file
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19cf1bf]

goroutine 1 [running]:
github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon.(*NodeStateStatusWriter).writeCheckpointFile(0xc00089afc0?, 0x0, {0x1eca779?, 0x32?})
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon/writer.go:218 +0x2bf
github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon.(*NodeStateStatusWriter).RunOnce(0xc00089afc0, {0x1eca779, 0x9}, 0x0)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon/writer.go:80 +0x30c
main.runStartCmd(0x314db80?, {0x1ec3d5e?, 0x0?, 0x0?})
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/cmd/sriov-network-config-daemon/start.go:191 +0xad3
github.com/spf13/cobra.(*Command).execute(0x314db80, {0x319b538, 0x0, 0x0})
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/github.com/spf13/cobra/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x314d5c0)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/github.com/spf13/cobra/command.go:968
main.main()
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/cmd/sriov-network-config-daemon/main.go:42 +0x25
```

**Comment by zeeke** [comment]
It seems like the operator is not able to create the SriovNetworkNodeState for the node `knode01.foo.bar.baz.com`. Can you provide the operator logs?

**Comment by SchSeba** [comment]
closing this one
